import { ChefTip, TipCategoryKey } from '@/app/types';

export interface CategoryInfo {
  key: TipCategoryKey;
  label_es: string;
  label_en: string;
  tag: string;
  color: string;
  bgLight: string;
  iconName: string;
}

export const CHEF_TIP_CATEGORIES: CategoryInfo[] = [
  {
    key: 'knife_skills',
    label_es: 'Cuchillos y Utensilios',
    label_en: 'Knife Skills & Tools',
    tag: '#Cuchillos',
    color: '#8B261E',
    bgLight: '#FBEBEA',
    iconName: 'Scissors',
  },
  {
    key: 'organization',
    label_es: 'Organización y Espacio',
    label_en: 'Mise en Place',
    tag: '#Organización',
    color: '#2B5A75',
    bgLight: '#EBF4F9',
    iconName: 'LayoutGrid',
  },
  {
    key: 'heat_control',
    label_es: 'Manejo del Fuego',
    label_en: 'Heat Control',
    tag: '#ManejoDelFuego',
    color: '#B85418',
    bgLight: '#FCF0E8',
    iconName: 'Flame',
  },
  {
    key: 'flavor_seasoning',
    label_es: 'Sabor y Sazón',
    label_en: 'Flavor & Seasoning',
    tag: '#SaborYSazón',
    color: '#4B6B2B',
    bgLight: '#EFF5E9',
    iconName: 'Sparkles',
  },
  {
    key: 'shortcuts_conservation',
    label_es: 'Conservación y Atajos',
    label_en: 'Storage & Shortcuts',
    tag: '#Atajos',
    color: '#654B78',
    bgLight: '#F3EDF7',
    iconName: 'Zap',
  },
  {
    key: 'baking',
    label_es: 'Repostería Casera',
    label_en: 'Home Baking',
    tag: '#ReposteriaHacks',
    color: '#9C6228',
    bgLight: '#FAF0E4',
    iconName: 'Cake',
  },
];

export const AUTHOR_LEAN_BORSINI = {
  id: '1afb8de4-9294-4f57-af9f-dc50b3e6e768',
  username: 'leanBorsini',
  avatar_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
};

const RAW_CHEF_TIPS: ChefTip[] = [
  // 🔪 Cuchillos y Utensilios
  {
    id: 'tip_knife_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'La regla del trapo húmedo bajo la tabla',
    title_en: 'The damp towel rule under your cutting board',
    summary_es: 'Nunca piques sobre una tabla que se tambalea. Coloca un paño de cocina húmedo o papel absorbente debajo para fijarla al instante.',
    summary_en: 'Never chop on a wobbling cutting board. Place a damp kitchen towel or paper towel underneath to anchor it instantly.',
    content_es: 'Una tabla inestable es la principal causa de accidentes domésticos con cuchillos. Al presionar sobre una superficie que desliza, la hoja pierde tracción y resbala hacia tus dedos. Un trapo húmedo crea succión natural por fricción y deja tu estación 100% segura en 2 segundos.',
    content_en: 'An unstable cutting board is the leading cause of home kitchen knife accidents. A damp cloth creates natural friction suction and locks your station firmly in place in seconds.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'tip_knife_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El agarre de pinza (Pinch Grip)',
    title_en: 'The chef pinch grip technique',
    summary_es: 'Olvida agarrar solo el mango: pinza la base de la hoja con el pulgar y el índice. Multiplicarás tu control, equilibrio y velocidad al cortar.',
    summary_en: 'Forget holding just the handle: pinch the blade base with thumb and index finger. You will multiply control, balance, and speed.',
    content_es: 'Sostener el cuchillo exclusivamente por el mango crea un punto de palanca débil y cansa la muñeca rápidamente. Al "pinzar" el talón de la hoja metálica con tu pulgar y el lateral del dedo índice, el cuchillo se convierte en una extensión natural de tu antebrazo.',
    content_en: 'Holding the knife solely by its handle causes wrist fatigue. Pinching the blade heel turns the knife into an extension of your forearm for effortless precision.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T10:15:00Z',
  },
  {
    id: 'tip_knife_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El mito del cuchillo afilado es peligroso',
    title_en: 'The myth: sharp knives are dangerous',
    summary_es: 'Un cuchillo desafilado es el que corta dedos: exige fuerza excesiva y resbala. Un filo vivo responde dócilmente con presión mínima.',
    summary_en: 'A dull knife is what cuts fingers: it requires brute force and slips. A sharp blade responds smoothly with minimal pressure.',
    content_es: 'Cuando un cuchillo no tiene filo, tienes que ejercer presión hacia abajo sobre pieles duras (como tomates o pimientos). En ese esfuerzo la hoja salta sin control. Con un cuchillo afilado, basta el propio peso del cuchillo y un movimiento de balanceo suave.',
    content_en: 'With a dull knife you exert heavy downward pressure, causing it to slip across skins like tomatoes. A truly sharp blade glides purely on its own weight and gentle motion.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T10:30:00Z',
  },
  {
    id: 'tip_knife_04',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Nunca uses tu sartén antiadherente a fuego máximo',
    title_en: 'Never use non-stick pans on high heat',
    summary_es: 'El teflón se degrada por encima de los 250°C. Reserva el antiadherente para huevos y pescados delicados a fuego suave; usa acero o hierro para sellar.',
    summary_en: 'PTFE coatings degrade above 250°C. Save non-stick pans for eggs and delicate fish on gentle heat; use cast iron or stainless steel for searing.',
    content_es: 'El calor extremo deteriora irreversiblemente las capas antiadherentes y libera compuestos volátiles indeseables. Para saltear a fuego vivo o conseguir una costra dorada crujiente en carnes, el acero inoxidable o hierro fundido son insuperables.',
    content_en: 'Extreme heat damages non-stick surfaces permanently. For golden crusts and high-heat stir frying, stainless steel or seasoned cast iron are unbeatable.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 50,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T10:45:00Z',
  },
  {
    id: 'tip_knife_05',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Dile adiós al prensador de ajos',
    title_en: 'Say goodbye to the garlic press',
    summary_es: 'La técnica del aplastado con el lateral de la hoja y una pizca de sal gruesa crea pasta de ajo sedosa en 15 segundos sin lavar utensilios imposibles.',
    summary_en: 'Crushing garlic with the side of your knife blade and coarse salt creates a silky garlic paste in 15 seconds without hard-to-clean presses.',
    content_es: 'Los prensadores de ajo dejan la mitad del producto atrapado en agujeros imposibles de lavar. Pela el diente, colócale una pizca de sal marina (que actúa como abrasivo mecánico natural) y arrastra el lateral plano del cuchillo varias veces en 45 grados. Obtendrás una emulsión aromática lista para salsas.',
    content_en: 'Garlic presses trap half the garlic. Flatten a peeled clove with your knife side, sprinkle coarse salt as a natural micro-abrasive, and scrape down. Silky, fragrant garlic paste.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T11:00:00Z',
  },
  {
    id: 'tip_knife_06',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'La física de la cuchara de madera',
    title_en: 'The physics of the wooden spoon',
    summary_es: 'Es el mejor instrumento para deglasear fondos de olla. Su borde plano y firme despega los azúcares caramelizados sin rayar nada ni calentar el mango.',
    summary_en: 'The best tool to deglaze pan fond. Its firm edge lifts caramelized sugars without scratching surfaces or conducting heat to your hand.',
    content_es: 'A diferencia de las cucharas metálicas que conducen el calor o las siliconas demasiado flexibles, la madera ofrece la resistencia justa para levantar el "fond" (los jugos dorados pegados) cuando viertes vino o caldo en el sartén.',
    content_en: 'Unlike silicone spatulas that flex too much or metal spoons that scratch, wood provides the ideal rigid resistance to lift sticky caramelized juices when splashing broth or wine.',
    category: 'knife_skills',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T11:15:00Z',
  },

  // 🧠 Organización y Espacio (Mise en Place)
  {
    id: 'tip_org_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El contenedor de desperdicios en tu tabla',
    title_en: 'The prep waste bowl right beside your board',
    summary_es: 'Ten un bol mediano al lado exclusivo para cáscaras y tallos. Evitarás 15 viajes al cubo de basura y mantendrás tu tabla 100% limpia.',
    summary_en: 'Keep a bowl next to your board solely for peelings and scraps. You will avoid 15 trips to the trash can and keep your board spotless.',
    content_es: 'El desorden mental en la cocina empieza cuando la tabla se llena de hojas de cebolla, cáscaras y semillas. Al arrojar cada desecho a un tazón dedicado en tu misma estación de trabajo, tu tabla permanece despejada y cocinas con fluidez de restaurante.',
    content_en: 'Clutter creates stress. Throwing peels and ends into a dedicated counter bowl keeps your work surface free, hygienic, and restaurant-ready.',
    category: 'organization',
    image_url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T11:30:00Z',
  },
  {
    id: 'tip_org_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'A.B.C: Always Be Cleaning (Limpia mientras cocinas)',
    title_en: 'A.B.C: Always Be Cleaning as you go',
    summary_es: '¿La cebolla tarda 5 minutos en pocharse? Lava la tabla y el bol. Llegar a la mesa sin una montaña de vajilla sucia cambia tu experiencia culinaria.',
    summary_en: 'Onions simmering for 5 minutes? Wash your board and knife. Sitting down to eat with an empty sink transforms your cooking experience.',
    content_es: 'El secreto de los cocineros profesionales no es fregar al final: es aprovechar los tiempos muertos de hervor y cocción lenta para enjuagar herramientas inmediatamente. Los restos frescos se quitan con agua en 3 segundos; si se secan, requieren 10 minutos de remojo.',
    content_en: 'Fresh food residues wash away in 3 seconds. Dried-on residue takes minutes of scrubbing. Use idle simmering windows to keep your sink clear.',
    category: 'organization',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T11:45:00Z',
  },
  {
    id: 'tip_org_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Recipientes Deli y cinta de carrocero',
    title_en: 'Deli containers & painter tape labeling',
    summary_es: 'El secreto de las brigadas de cocina: recipientes translúcidos apilables y cinta adhesiva de papel para rotular fechas sin dejar residuos pegajosos.',
    summary_en: 'The professional kitchen secret: stackable deli containers and painter tape to date prepped foods without sticky residue.',
    content_es: 'Olvídate de tapas desparejadas. Un set de recipientes de polipropileno con tapa universal y un rollo de cinta azul o de enmascarar te permite ver qué hay dentro de tu nevera a primera vista, evitando el desperdicio de comida.',
    content_en: 'End the mismatched lid nightmare. Clear uniform containers labeled with easily peelable tape let you scan your fridge inventory in seconds.',
    category: 'organization',
    image_url: 'https://images.unsplash.com/photo-1584990347449-3543d8336d3c?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T12:00:00Z',
  },
  {
    id: 'tip_org_04',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El orden de picado sí altera el plato (y tu tiempo)',
    title_en: 'Cutting order matters: dry first, meat last',
    summary_es: 'Pica primero ingredientes secos (hierbas, frutos secos), luego vegetales aromáticos y al final carnes crudas. Ahorrarás lavar la tabla 3 veces.',
    summary_en: 'Chop dry items first (nuts, herbs), then aromatic veggies, and raw proteins last. You will avoid scrubbing your board multiple times.',
    content_es: 'Si cortas pollo crudo de entrada, estás obligado a higienizar a fondo tabla y cuchillo con jabón antes de picar la cebolla. Siguiendo la secuencia Seco -> Verduras -> Proteínas, un simple repaso con un paño entre pasos es suficiente hasta el lavado final.',
    content_en: 'Cutting chicken first forces an immediate board sanitization. Planning sequence from Dry -> Veggies -> Raw Meat streamlines workflow seamlessly.',
    category: 'organization',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T12:15:00Z',
  },

  // 🔥 Manejo de Temperatura y Fuego
  {
    id: 'tip_heat_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El sartén habla: aprende a escuchar el chillido',
    title_en: 'Listen to the sizzle: the pan talks',
    summary_es: 'Añadir comida a un sartén tibio hace que absorba grasa y se pegue. Espera a que el aceite brille suavemente y emita un crepitar vivo al contacto.',
    summary_en: 'Putting ingredients into a warm pan makes them absorb oil and stick. Wait until oil shimmers and produces a confident sizzle on contact.',
    content_es: 'El sonido del sellado es agua vaporizándose instantáneamente bajo el alimento, creando un micro-colchón de vapor que impide que las proteínas se adhieran al metal. Si al echar el filete no hay ruido, retíralo y calienta el sartén 1 minuto más.',
    content_en: 'The sizzle is moisture flash-steaming, lifting the food and preventing sticking. Silence on contact means your pan is too cold: pull it back and heat up.',
    category: 'heat_control',
    image_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T12:30:00Z',
  },
  {
    id: 'tip_heat_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'No abarrotes el sartén (La regla del espacio)',
    title_en: "Don't overcrowd the pan (The spacing rule)",
    summary_es: 'Si saturas la superficie, los ingredientes liberan vapor y se hierven en lugar de dorarse. Deja al menos 25% de espacio libre o cocina en 2 tandas.',
    summary_en: 'Crowding the pan traps moisture, causing food to steam rather than brown. Leave at least 25% open space or cook in batches.',
    content_es: 'Para que ocurra el dorado caramelizado (reacción de Maillard), la temperatura del fondo debe mantenerse por encima de 140°C. Si llenas el sartén hasta el borde, el calor cae en picada y los champiñones o carne nadarán en agua grisácea.',
    content_en: 'For true caramelization, pan surface must stay above 140°C. Overcrowding drops heat drastically, resulting in gray steamed mushrooms or stewed meat.',
    category: 'heat_control',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T12:45:00Z',
  },
  {
    id: 'tip_heat_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'La Reacción de Maillard: seca tus proteínas',
    title_en: 'The Maillard reaction: dry your proteins first',
    summary_es: 'El agua es enemiga del dorado. Seca carnes, pescados y tofu con papel de cocina antes de que toquen el sartén caliente para lograr costras crujientes.',
    summary_en: 'Water is the enemy of browning. Pat meats, fish, and tofu thoroughly dry with paper towels before hitting the pan for golden crusts.',
    content_es: 'El agua hierve a 100°C, mientras que los deliciosos compuestos de sabor Maillard se crean a partir de 140°C-160°C. Toda gota de humedad superficial obligará a la sartén a gastar energía evaporando agua antes de empezar a dorar.',
    content_en: 'Water boils at 100°C, whereas flavor-packed Maillard reactions require 140°C+. Any surface moisture wastes energy boiling before browning can begin.',
    category: 'heat_control',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T13:00:00Z',
  },
  {
    id: 'tip_heat_04',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Saca las carnes de la nevera 20 minutos antes',
    title_en: 'Bring meat to room temp 20 minutes before',
    summary_es: 'El choque térmico entre una carne fría de nevera (4°C) y el sartén hirviendo endurece las fibras y deja el centro crudo y el exterior quemado.',
    summary_en: 'Thermal shock from fridge-cold meat (4°C) onto hot pans tightens muscle fibers, leaving the core raw and exterior overcooked.',
    content_es: 'Atemperar permite que el calor penetre suavemente de forma uniforme. Notarás un corte mucho más tierno, jugoso y con un punto de cocción homogéneo de borde a centro.',
    content_en: 'Tempering allows heat to travel evenly throughout the cut. You will achieve juicier, tender results with edge-to-edge even doneness.',
    category: 'heat_control',
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T13:15:00Z',
  },
  {
    id: 'tip_heat_05',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Controla el fuego, no dejes que el fuego te controle',
    title_en: 'Control the heat, do not let heat control you',
    summary_es: 'La perilla del quemador no es un interruptor de encendido/apagado. Aprende a bajar a fuego medio-bajo para confitar y subir solo al sellar.',
    summary_en: 'Burner dials are not on/off switches. Modulate down to gentle medium-low to caramelize onions and raise high only for quick searing.',
    content_es: 'El error más común en cocineros principiantes es cocinar todo a fuego máximo para "ir más rápido". La cocción rápida quema el exterior antes de desarrollar dulzor y amargor equilibrado en sofritos.',
    content_en: 'Novice cooks tend to blast maximum flame trying to cook faster. Gentle heat sweetens onions and renders fat; blast only for final crisping.',
    category: 'heat_control',
    image_url: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T13:30:00Z',
  },

  // 🧂 Sabor, Sal y Balances de Sabor
  {
    id: 'tip_flavor_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Saltea desde las alturas (High-altitude salting)',
    title_en: 'Salt from high above for even dispersion',
    summary_es: 'Dejar caer los granos de sal desde 30 cm de altura crea una lluvia homogénea. Evitarás parches salados y un bocado insípido junto a otro amargo.',
    summary_en: 'Letting salt rain down from 30 cm (12 inches) creates an even blanket. You will eliminate salty hotspots and bland pockets.',
    content_es: 'Al salar pegado a la sartén, la sal cae en cúmulos concentrados. Elevar la mano permite que la resistencia del aire disperse los cristales de sal fina o marina de forma matemáticamente uniforme en todo el plato.',
    content_en: 'Salting close to the pan dumps grains in clumps. Elevating your hand lets air scatter crystals evenly over the whole surface.',
    category: 'flavor_seasoning',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T13:45:00Z',
  },
  {
    id: 'tip_flavor_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Si a tu plato le falta algo, no es sal: es ÁCIDO',
    title_en: 'When your dish lacks something, it needs ACID, not salt',
    summary_es: '¿La sopa o salsa sabe "plana" y pesada? Unas gotas de limón o vinagre de jerez cortan la grasa y encienden los sabores apagados al instante.',
    summary_en: 'Does your soup or sauce feel heavy or flat? A squeeze of lemon or sherry vinegar cuts through fat and awakens dormant flavors immediately.',
    content_es: 'El ácido estimula la salivación en las papilas gustativas laterales, haciendo que percibas todos los demás sabores con nitidez. Antes de añadir una tercera cucharadita de sal, prueba con media cucharadita de vinagre de manzana o zumo de lima.',
    content_en: 'Acids trigger salivary response, heightening perception of sweetness and umami. Before dumping more salt, balance heavy stews with citrus or vinegar.',
    category: 'flavor_seasoning',
    image_url: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T14:00:00Z',
  },
  {
    id: 'tip_flavor_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'A.B.T: Always Be Tasting (Prueba en cada fase)',
    title_en: 'A.B.T: Always Be Tasting at every stage',
    summary_es: 'No esperes a servir en la mesa para saber si falta sazón. Prueba el sofrito, la salsa reducida y el caldo antes de emplatar.',
    summary_en: 'Never wait until plating to check seasoning. Taste the sauteed aromatics, reducing sauce, and simmering broth at each benchmark.',
    content_es: 'La sal interactúa de modo distinto según el alimento se cocina. La sal agregada al principio penetra el interior de las verduras y carnes; la sal agregada al final solo cubre la superficie. Probar constantemente entrena tu paladar de chef.',
    content_en: 'Early salt penetrates cell walls deeply; late salt only touches outer coatings. Tasting throughout builds culinary intuition and avoids surprises.',
    category: 'flavor_seasoning',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T14:15:00Z',
  },
  {
    id: 'tip_flavor_04',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El oro líquido de los amantes de la pasta',
    title_en: 'The liquid gold: pasta cooking water',
    summary_es: 'Nunca escurras la pasta directo al desagüe: reserva media taza de agua de cocción. Su almidón gelatinizado emulsiona salsas sedosas y brillantes.',
    summary_en: 'Never dump pasta water down the sink: save half a cup. Its gelatinized starches emulsify fatty sauces into glossy restaurant perfection.',
    content_es: '¿Por qué en los restaurantes italianos la salsa se abraza al fideo y en casa queda en el fondo del plato? El agua de pasta rica en almidón actúa como ligante entre las grasas del aceite o mantequilla y el tomate o queso (mantecatura).',
    content_en: 'Why do Italian sauces coat noodles like silk? Pasta starch bonds fats and liquids into a creamy, glossy emulsion without needing heavy cream.',
    category: 'flavor_seasoning',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T14:30:00Z',
  },
  {
    id: 'tip_flavor_05',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Guarda las cortezas de queso Parmesano',
    title_en: 'Save parmesan cheese rinds for broths',
    summary_es: 'No tires la corteza dura del queso. Congélala y agrégala a caldos de pollo, minestrone o salsa boloñesa para una bomba de umami natural.',
    summary_en: 'Do not toss hard cheese rinds. Freeze them and simmer into chicken broths, minestrone, or bolognese for an umami flavor bomb.',
    content_es: 'Las cortezas de Parmigiano Reggiano están repletas de glutamato monosódico natural formado durante meses de curación. Al infusionarse lentamente en un caldo caliente, aportan profundidad y sabor sin derretirse de forma pastosa.',
    content_en: 'Aged parmesan rinds pack concentrated natural glutamates. Simmering them gently enriches winter soups and sauces with profound depth.',
    category: 'flavor_seasoning',
    image_url: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T14:45:00Z',
  },

  // 🧄 Conservación y Preparación Rápida
  {
    id: 'tip_short_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Las hierbas frescas se tratan como flores',
    title_en: 'Treat fresh tender herbs like cut flowers',
    summary_es: 'Corta 1 cm del tallo de cilantro o perejil, ponlos en un vaso con 2 dedos de agua en la puerta del refrigerador y cúbrelos con una bolsa holgada.',
    summary_en: 'Trim cilantro and parsley stems, place them in a glass with an inch of water in your fridge door, and loosely cover with a plastic bag.',
    content_es: 'En plástico cerrado sudan y se pudren en 4 días; secas se marchitan en 2. Manteniendo sus tallos hidratados como un ramo de flores, permanecen turgentes, verdes y aromáticas hasta por 3 semanas completas.',
    content_en: 'Sealed bags rot herbs in 4 days. Storing stems in water with loose air circulation keeps them crisp, vibrant, and fragrant for up to 3 weeks.',
    category: 'shortcuts_conservation',
    image_url: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T15:00:00Z',
  },
  {
    id: 'tip_short_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'El truco del frasco para pelar cabezas de ajo',
    title_en: 'The glass jar shake trick for peeling garlic',
    summary_es: 'Separa los dientes de ajo, mételos dentro de un frasco de vidrio o dos boles metálicos y agita enérgicamente 10 segundos. Pieles desprendidas al 100%.',
    summary_en: 'Separate cloves, drop them into a jar or between two metal bowls, and shake vigorously for 10 seconds. Skins pop off effortlessly.',
    content_es: 'El impacto cinético de los dientes contra las paredes rompe la tensión superficial de las pieles secas sin dañar el bulbo ni dejarte olor a ajo en las uñas durante días.',
    content_en: 'Kinetic impact shatters papery skins clean off the cloves in seconds without garlic oil sticking to your fingernails.',
    category: 'shortcuts_conservation',
    image_url: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T15:15:00Z',
  },
  {
    id: 'tip_short_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Los tomates nunca van en el refrigerador',
    title_en: 'Tomatoes never belong in the refrigerator',
    summary_es: 'El frío por debajo de 12°C destruye las enzimas aromáticas y vuelve la pulpa harinosa. Mantenlos a temperatura ambiente boca abajo.',
    summary_en: 'Cold below 12°C deactivates flavor-producing enzymes and makes texture mealy. Store them at room temperature stem-side down.',
    content_es: 'El compuesto que da el característico olor a tomate maduro (Z-3-hexenal) se desactiva permanentemente en frío. Guárdalos en una frutera y sólo refrigéralos si ya han sido cortados o si están excesivamente maduros.',
    content_en: 'Refrigeration suppresses volatile aroma synthesis in fresh tomatoes. Keep them counter-side to savor sweet acidity and firm texture.',
    category: 'shortcuts_conservation',
    image_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 40,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T15:30:00Z',
  },
  {
    id: 'tip_short_04',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Congela tus caldos y vinos en cubiteras de hielo',
    title_en: 'Freeze broths and leftover wine in ice cube trays',
    summary_es: '¿Sobró un poco de vino o caldo casero? Congélalo en cubos. Cada cubo equivale a 2 cucharadas listas para enriquecer salsas rápidas.',
    summary_en: 'Leftover wine or homemade stock? Freeze in ice trays. Each cube delivers 2 tablespoons ready to enrich pan sauces on demand.',
    content_es: 'En lugar de dejar avinagrar una botella abierta en la puerta de la nevera o tirar 200 ml de caldo, porcionar en cubitos te da potenciadores instantáneos para desglasar sartenes en cualquier cena entre semana.',
    content_en: 'Prevent wine oxidation and broth spoilage. Pop 2 frozen cubes straight into a hot pan for instantaneous pan gravy and pan reduction.',
    category: 'shortcuts_conservation',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T15:45:00Z',
  },

  // 🍰 Repostería para Cocineros Caseros
  {
    id: 'tip_baking_01',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'La repostería es química: usa báscula gramera',
    title_en: 'Baking is chemistry: always use a gram scale',
    summary_es: 'Una "taza" de harina puede pesar entre 110g y 160g según cómo la compactes. Pesar en gramos garantiza bizcochos esponjosos siempre.',
    summary_en: 'A "cup" of flour can weigh anywhere from 110g to 160g depending on packing. Digital gram scales guarantee fluffy cakes every single time.',
    content_es: 'En cocina salada improvisar funciona; en repostería la proporción harina-grasa-azúcar-líquido determina la formación de gluten y leudado. Una báscula digital cuesta muy poco y revoluciona tus resultados de horneado.',
    content_en: 'Cooking is art; baking is precision chemistry. Cup measurements fluctuate drastically. A simple kitchen scale guarantees consistent perfection.',
    category: 'baking',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T16:00:00Z',
  },
  {
    id: 'tip_baking_02',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Ingredientes a temperatura ambiente significan EXACTAMENTE eso',
    title_en: 'Room temperature ingredients mean EXACTLY that',
    summary_es: 'Huevos o leche fríos cortan la emulsión de mantequilla batida con azúcar. Sácalos 45 minutos antes o entibia los huevos en agua templada.',
    summary_en: 'Cold eggs or milk curdle creamed butter and sugar emulsions. Pull them out 45 minutes ahead or warm eggs in lukewarm water for 5 minutes.',
    content_es: 'Cuando bates mantequilla y azúcar atrapas microburbujas de aire. Si agregas un huevo a 4°C, solidificas la grasa al instante y la mezcla se corta, perdiendo aire y arruinando la miga esponjosa.',
    content_en: 'Creamed butter traps air. Cold liquids coagulate milk fats instantly, causing splits and resulting in dense, sunken baked goods.',
    category: 'baking',
    image_url: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 45,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T16:15:00Z',
  },
  {
    id: 'tip_baking_03',
    author_id: AUTHOR_LEAN_BORSINI.id,
    author_username: AUTHOR_LEAN_BORSINI.username,
    profiles: AUTHOR_LEAN_BORSINI,
    title_es: 'Espolvorea harina en las frutas antes de hornear',
    title_en: 'Dust fruits with flour before folding into batter',
    summary_es: '¿Tus arándanos o chispas de chocolate se van al fondo del molde? Rebózalos en 1 cucharada de harina para que queden suspendidos homogéneamente.',
    summary_en: 'Do blueberries or chocolate chips sink to the pan bottom? Toss them in a spoonful of flour so they stay evenly suspended throughout.',
    content_es: 'La capa fina de harina crea fricción con la masa densa del pastel o muffin, impidiendo que la gravedad los arrastre a la base antes de que la estructura del bizcocho cuaje en el horno.',
    content_en: 'A light dusting of flour creates surface tension with wet batter, holding fruit in place until heat sets the crumb structure.',
    category: 'baking',
    image_url: 'https://images.unsplash.com/photo-1506459225024-1428097a7e18?w=800&auto=format&fit=crop&q=80',
    read_time_seconds: 35,
    likes_count: 0,
    avg_rating: 0,
    ratings_count: 0,
    created_at: '2026-09-08T16:30:00Z',
  },
];

/**
 * Lista canónica de tips iniciales.
 * Todos arrancan estrictamente en 0 'me gusta', 0 puntuación y 0 comentarios reales.
 */
export const INITIAL_CHEF_TIPS: ChefTip[] = RAW_CHEF_TIPS.map((tip) => ({
  ...tip,
  likes_count: 0,
  avg_rating: 0,
  ratings_count: 0,
  comments_count: 0,
  user_liked: false,
  user_rating: 0,
}));
