import { Recipe, Ingredient } from '../app/types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec_1',
    user_id: 'user_default',
    profiles: {
      id: 'user_default',
      username: 'chef_elena',
      avatar_url: '',
    },
    title_es: 'Tortilla de Patatas Tradicional',
    title_en: 'Traditional Spanish Potato Omelette',
    category: 'Plato Principal',
    prep_time: 30,
    servings: 4,
    description_es: 'Clásica tortilla española jugosa y tierna, preparada con patatas doradas a fuego lento y cebolla caramelizada.',
    description_en: 'Classic juicy Spanish potato omelette made with slow-cooked golden potatoes and caramelized onions.',
    instructions_es: '1. Pelar y cortar las patatas y la cebolla en láminas finas.\n2. Pochar en abundante aceite de oliva a fuego medio-bajo hasta que estén tiernas (unos 20 minutos).\n3. Batir los huevos en un bol grande con una pizca generosa de sal.\n4. Escurrir las patatas y cebolla e incorporarlas al huevo batido; dejar reposar 5 minutos.\n5. Cuajar en una sartén antiadherente con unas gotas de aceite durante 2 minutos por lado.',
    instructions_en: '1. Peel and slice the potatoes and onion thinly.\n2. Poach in olive oil over medium-low heat until tender (about 20 minutes).\n3. Beat the eggs in a large bowl with salt.\n4. Drain the potatoes and mix into the beaten eggs; rest for 5 minutes.\n5. Cook in a non-stick skillet for 2 minutes on each side until golden and creamy inside.',
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    image_url: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=800&q=80',
    dietary_tags: ['Sin Gluten', 'Vegetariano', 'Sin Frutos Secos'],
    created_at: '2025-01-10T12:00:00.000Z',
  },
  {
    id: 'rec_2',
    user_id: 'user_default',
    profiles: {
      id: 'user_default',
      username: 'leanBorsini',
      avatar_url: '',
    },
    title_es: 'Pasta al Pesto Genovés con Tomates Cherry',
    title_en: 'Genoese Pesto Pasta with Cherry Tomatoes',
    category: 'Pasta',
    prep_time: 20,
    servings: 2,
    description_es: 'Espaguetis al dente bañados en salsa pesto casera de albahaca fresca, piñones tostados, parmesano y tomates salteados.',
    description_en: 'Al dente spaghetti tossed in fresh homemade basil pesto with toasted pine nuts, parmesan, and sautéed cherry tomatoes.',
    instructions_es: '1. Cocinar la pasta en abundante agua con sal según las instrucciones del paquete.\n2. En un mortero o procesador, triturar albahaca, ajo, piñones, parmesano y aceite de oliva virgen extra.\n3. Saltear los tomates cherry partidos a la mitad en una sartén.\n4. Mezclar la pasta escurrida con el pesto y un poco de agua de cocción. Coronar con los tomates.',
    instructions_en: '1. Cook pasta in boiling salted water according to package instructions.\n2. Blend basil, garlic, pine nuts, parmesan, and extra virgin olive oil.\n3. Sauté cherry tomatoes in a pan until blistered.\n4. Toss pasta with pesto sauce and a splash of pasta water. Top with tomatoes.',
    youtube_url: '',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    dietary_tags: ['Vegetariano'],
    created_at: '2025-01-12T14:30:00.000Z',
  },
  {
    id: 'rec_3',
    user_id: 'user_default',
    profiles: {
      id: 'user_default',
      username: 'maria_cocina',
      avatar_url: '',
    },
    title_es: 'Bowl de Quinoa, Aguacate y Garbanzos Crujientes',
    title_en: 'Crispy Chickpea, Avocado & Quinoa Bowl',
    category: 'Ensaladas',
    prep_time: 25,
    servings: 2,
    description_es: 'Un bowl nutritivo, colorido y 100% vegetal con garbanzos especiados al horno, espinacas tiernas y vinagreta de tahini.',
    description_en: 'A vibrant, nutrient-dense plant-based bowl with spiced roasted chickpeas, baby spinach, avocado and tahini dressing.',
    instructions_es: '1. Enjuagar y cocer la quinoa en agua durante 15 minutos.\n2. Mezclar los garbanzos cocidos con pimentón, comino, sal y aceite de oliva; hornear a 200°C por 18 min.\n3. Cortar el aguacate, pepino y tomates cherry.\n4. Montar el bowl colocando la base de quinoa, espinacas, verduras y garbanzos crujientes. Aliñar con tahini y limón.',
    instructions_en: '1. Rinse and cook quinoa in water for 15 minutes.\n2. Toss cooked chickpeas with paprika, cumin, salt, and olive oil; roast at 200°C for 18 min.\n3. Slice avocado, cucumber, and cherry tomatoes.\n4. Assemble the bowl with quinoa base, spinach, fresh vegetables, and crispy chickpeas. Drizzle with tahini lemon dressing.',
    youtube_url: '',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    dietary_tags: ['Sin Gluten', 'Sin Lácteos', 'Vegetariano', 'Vegano', 'Sin Frutos Secos'],
    created_at: '2025-01-15T09:15:00.000Z',
  },
  {
    id: 'rec_4',
    user_id: 'user_default',
    profiles: {
      id: 'user_default',
      username: 'carlos_grill',
      avatar_url: '',
    },
    title_es: 'Tacos de Pollo Marinado al Limón y Cilantro',
    title_en: 'Cilantro Lime Marinated Chicken Tacos',
    category: 'Mexicana',
    prep_time: 25,
    servings: 3,
    description_es: 'Sabrosos tacos en tortilla de maíz con pechuga de pollo marinada en jugo de lima, ajo, cilantro y cebolla morada encurtida.',
    description_en: 'Flavorful corn tortilla tacos with chicken breast marinated in fresh lime juice, garlic, cilantro, and pickled red onions.',
    instructions_es: '1. Cortar la pechuga en tiras y marinar con jugo de lima, ajo picado, cilantro, orégano y sal.\n2. Saltear a fuego vivo en una sartén o plancha hasta que esté dorado y jugoso.\n3. Calentar las tortillas de maíz en una sartén seca.\n4. Servir el pollo sobre las tortillas con cebolla morada encurtida, rodajas de rábano y salsa al gusto.',
    instructions_en: '1. Cut chicken into strips and marinate with lime juice, minced garlic, cilantro, oregano, and salt.\n2. Sear in a hot skillet until golden and thoroughly cooked.\n3. Warm corn tortillas on a dry skillet.\n4. Assemble tacos with chicken, pickled red onion, sliced radishes, and salsa.',
    youtube_url: '',
    image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    dietary_tags: ['Sin Gluten', 'Sin Lácteos', 'Sin Frutos Secos'],
    created_at: '2025-01-18T18:40:00.000Z',
  },
];

export const SAMPLE_INGREDIENTS: Record<string, Ingredient[]> = {
  rec_1: [
    { name_es: 'Patatas / Papas', name_en: 'Potatoes', amount: 4, unit: 'unidades', aisle: 'Verdulería' },
    { name_es: 'Huevos de campo', name_en: 'Eggs', amount: 6, unit: 'unidades', aisle: 'Lácteos y Huevos' },
    { name_es: 'Cebolla dulce', name_en: 'Sweet Onion', amount: 1, unit: 'unidad', aisle: 'Verdulería' },
    { name_es: 'Aceite de oliva virgen extra', name_en: 'Olive oil', amount: 200, unit: 'ml', aisle: 'Aceites y Condimentos' },
    { name_es: 'Sal marina', name_en: 'Sea salt', amount: 1, unit: 'pizca', aisle: 'Aceites y Condimentos' },
  ],
  rec_2: [
    { name_es: 'Espaguetis', name_en: 'Spaghetti', amount: 250, unit: 'g', aisle: 'Pastas y Legumbres' },
    { name_es: 'Albahaca fresca', name_en: 'Fresh Basil', amount: 50, unit: 'g', aisle: 'Verdulería' },
    { name_es: 'Queso Parmesano rallado', name_en: 'Parmesan cheese', amount: 60, unit: 'g', aisle: 'Lácteos y Huevos' },
    { name_es: 'Piñones tostados', name_en: 'Pine nuts', amount: 30, unit: 'g', aisle: 'Frutos Secos' },
    { name_es: 'Diente de ajo', name_en: 'Garlic clove', amount: 1, unit: 'unidad', aisle: 'Verdulería' },
    { name_es: 'Tomates cherry', name_en: 'Cherry tomatoes', amount: 150, unit: 'g', aisle: 'Verdulería' },
    { name_es: 'Aceite de oliva virgen extra', name_en: 'Olive oil', amount: 50, unit: 'ml', aisle: 'Aceites y Condimentos' },
  ],
  rec_3: [
    { name_es: 'Quinoa tricolor', name_en: 'Quinoa', amount: 150, unit: 'g', aisle: 'Pastas y Legumbres' },
    { name_es: 'Garbanzos cocidos', name_en: 'Cooked chickpeas', amount: 200, unit: 'g', aisle: 'Conservas' },
    { name_es: 'Aguacate maduro', name_en: 'Avocado', amount: 1, unit: 'unidad', aisle: 'Verdulería' },
    { name_es: 'Espinacas baby', name_en: 'Baby spinach', amount: 80, unit: 'g', aisle: 'Verdulería' },
    { name_es: 'Tahini (pasta de sésamo)', name_en: 'Tahini', amount: 2, unit: 'cucharadas', aisle: 'Salsas y Aderezos' },
    { name_es: 'Limón', name_en: 'Lemon', amount: 1, unit: 'unidad', aisle: 'Verdulería' },
  ],
  rec_4: [
    { name_es: 'Pechuga de pollo limpia', name_en: 'Chicken breast', amount: 400, unit: 'g', aisle: 'Carnicería' },
    { name_es: 'Tortillas de maíz', name_en: 'Corn tortillas', amount: 6, unit: 'unidades', aisle: 'Panadería' },
    { name_es: 'Limas frescas', name_en: 'Fresh limes', amount: 2, unit: 'unidades', aisle: 'Verdulería' },
    { name_es: 'Cilantro fresco', name_en: 'Fresh cilantro', amount: 1, unit: 'manojo', aisle: 'Verdulería' },
    { name_es: 'Cebolla morada', name_en: 'Red onion', amount: 1, unit: 'unidad', aisle: 'Verdulería' },
    { name_es: 'Dientes de ajo', name_en: 'Garlic cloves', amount: 2, unit: 'unidades', aisle: 'Verdulería' },
  ],
};
